version: '3.8'

services:
  dionaea:
    image: dinotools/dionaea
    container_name: dionaea_honeypot
    restart: always
    ports:
      - "2121:21"
      - "8080:80"
      - "3306:3306"
    volumes:
      - ./dionaea/etc:/opt/dionaea/etc
      - ./dionaea/lib:/opt/dionaea/var/lib
      - ./dionaea/log:/opt/dionaea/var/log
    environment:
      - TZ=Asia/Ho_Chi_Minh

  # webservice:
  #   image: nginx:latest
  #   container_name: web_target
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./web_content:/usr/share/nginx/html
  #   networks:
  #     honeypot_net:
# networks:
#   honeypot_net:
#     driver: bridge
