services:
  dionaea:
    image: dinotools/dionaea
    container_name: dionaea_honeypot
    restart: always
    ports:
      - "2121:21"
      - "8080:80"
      - "3306:3306"
    volumes:
      - ./honeypot/etc:/opt/dionaea/etc
      - ./honeypot/lib:/opt/dionaea/var/lib
      - ./honeypot/log:/opt/dionaea/var/log
    environment:
      - TZ=Asia/Ho_Chi_Minh
    networks:
      honeypot_network:

networks:
  honeypot_network:
    driver: bridge
